title: Gameboard Help Documentation
description: Here you can find the Gameboard help documentation organized by role: participant, observer, moderator, game designer, and challenge designer.
theme: jekyll-theme-minimal
